
// 365 daily compliments for Isabel - human-like love comments
export const DAILY_COMPLIMENTS = [
  // January (31 days)
  "Your laugh is the most beautiful sound in the world",
  "You make ordinary moments feel magical",
  "Your kindness touches everyone around you",
  "You have the most gorgeous eyes I've ever seen",
  "Your smile could light up the darkest room",
  "You're incredibly smart and it's so attractive",
  "Your hugs feel like home to me",
  "You make me want to be a better person",
  "Your voice is like music to my ears",
  "You're beautiful inside and out",
  "Your heart is pure gold",
  "You make everything better just by being there",
  "Your creativity amazes me every day",
  "You're the most caring person I know",
  "Your strength inspires me constantly",
  "You have such a gentle soul",
  "Your passion for life is contagious",
  "You make me feel so loved and appreciated",
  "Your intelligence is incredibly sexy",
  "You're my favorite person to talk to",
  "Your optimism brightens my whole day",
  "You have the softest hands",
  "Your dreams are beautiful and so are you",
  "You make me laugh until my stomach hurts",
  "Your empathy makes you so special",
  "You're absolutely stunning when you concentrate",
  "Your love makes me feel invincible",
  "You have the most beautiful heart",
  "Your presence calms my anxious mind",
  "You're perfect exactly as you are",
  "Your energy is absolutely infectious",

  // February (28 days)
  "You make my heart skip beats",
  "Your beauty takes my breath away",
  "You're the sweetest person alive",
  "Your love is my safe haven",
  "You make me believe in fairy tales",
  "Your touch sends shivers down my spine",
  "You're my favorite hello and hardest goodbye",
  "Your soul is absolutely beautiful",
  "You make love feel effortless",
  "Your kisses are pure magic",
  "You're the answer to prayers I never knew I had",
  "Your love story with me is my favorite",
  "You make my world complete",
  "Your heart is my favorite place to be",
  "You're the reason I believe in love",
  "Your love feels like coming home",
  "You make every day feel like Valentine's Day",
  "Your affection melts my heart",
  "You're my person, my everything",
  "Your love is the best gift I've ever received",
  "You make romance feel real",
  "Your devotion means everything to me",
  "You're the love of my life",
  "Your tenderness makes me feel cherished",
  "You make my heart feel full",
  "Your love is my greatest treasure",
  "You're my soulmate and best friend",
  "Your love makes me feel alive",

  // March (31 days)
  "You bloom beautifully like spring flowers",
  "Your growth inspires me every day",
  "You bring fresh energy to everything",
  "Your resilience is absolutely amazing",
  "You make new beginnings feel exciting",
  "Your hope keeps me going",
  "You're like sunshine after winter",
  "Your renewal spirit is contagious",
  "You make change feel beautiful",
  "Your fresh perspective amazes me",
  "You bring life to everything you touch",
  "Your optimism is my favorite thing",
  "You make every season better",
  "Your warmth melts away all my worries",
  "You're like a breath of fresh air",
  "Your positive energy is incredible",
  "You make growth look graceful",
  "Your spirit is eternally youthful",
  "You bring color to my gray days",
  "Your vitality is absolutely magnetic",
  "You make rebirth feel possible",
  "Your enthusiasm is infectious",
  "You're my favorite season of life",
  "Your joy makes everything brighter",
  "You make transformation beautiful",
  "Your light guides me through darkness",
  "You're the spring in my step",
  "Your love makes everything bloom",
  "You bring hope to hopeless moments",
  "Your spirit never fails to amaze me",
  "You make every day feel like a fresh start",

  // April (30 days)
  "You're as refreshing as April rain",
  "Your laughter is like birds singing",
  "You make everything feel possible",
  "Your gentleness is so precious",
  "You bring peace to my chaotic world",
  "Your wisdom beyond your years amazes me",
  "You make simple moments special",
  "Your grace under pressure is beautiful",
  "You're my favorite part of every day",
  "Your thoughtfulness never goes unnoticed",
  "You make me feel so grateful",
  "Your spontaneity keeps life exciting",
  "You're incredibly talented at everything",
  "Your dedication is so admirable",
  "You make hard things look easy",
  "Your patience with me is endless",
  "You're the most genuine person I know",
  "Your loyalty means the world to me",
  "You make me feel so understood",
  "Your support gives me strength",
  "You're my biggest cheerleader",
  "Your belief in me changes everything",
  "You make me feel capable of anything",
  "Your encouragement lifts me up",
  "You're my safe space in this world",
  "Your understanding heart comforts me",
  "You make vulnerability feel safe",
  "Your acceptance of me is everything",
  "You're the calm in my storm",
  "Your love makes me feel worthy",

  // May (31 days)
  "You're as beautiful as May flowers",
  "Your birthday month suits you perfectly",
  "You make everything feel celebratory",
  "Your special day should last all month",
  "You deserve all the happiness in the world",
  "Your birth was a gift to everyone",
  "You make May even more beautiful",
  "Your existence makes the world better",
  "You're worth celebrating every single day",
  "Your life brings so much joy to others",
  "You make growing older look graceful",
  "Your wisdom grows more beautiful each year",
  "You're aging like fine wine",
  "Your maturity is incredibly attractive",
  "You make every year better than the last",
  "Your journey through life inspires me",
  "You're becoming more amazing each day",
  "Your evolution is beautiful to witness",
  "You make time feel precious",
  "Your memories with me are treasures",
  "You create the most beautiful moments",
  "Your presence is the best present",
  "You make celebrations more meaningful",
  "Your joy is absolutely contagious",
  "You deserve to be spoiled every day",
  "Your happiness is my priority",
  "You make wishes come true",
  "Your dreams are worth celebrating",
  "You bring magic to ordinary days",
  "Your smile is my favorite birthday gift",
  "You make life feel like a celebration",

  // June (30 days)
  "You're as warm as summer sunshine",
  "Your energy is absolutely radiant",
  "You make everything feel bright",
  "Your warmth melts my heart",
  "You bring light to every situation",
  "Your glow is absolutely stunning",
  "You make summer feel eternal",
  "Your brightness outshines the sun",
  "You're my favorite source of vitamin D",
  "Your radiance is natural and beautiful",
  "You make hot days feel perfect",
  "Your sunny disposition is infectious",
  "You bring warmth to cold hearts",
  "Your light guides me home",
  "You make everything golden",
  "Your presence feels like vacation",
  "You're my favorite summer memory",
  "Your joy feels like endless summer",
  "You make relaxation feel natural",
  "Your carefree spirit is beautiful",
  "You bring adventure to my life",
  "Your spontaneity makes life exciting",
  "You're my favorite travel companion",
  "Your wanderlust inspires me",
  "You make exploration feel safe",
  "Your curiosity about the world amazes me",
  "You bring excitement to routine days",
  "Your zest for life is contagious",
  "You make memories worth keeping",
  "You're my favorite summer love",

  // July (31 days)
  "You're as dazzling as fireworks",
  "Your independence is so attractive",
  "You make freedom feel beautiful",
  "Your strength is absolutely inspiring",
  "You celebrate life in the best way",
  "Your patriotic spirit is adorable",
  "You make traditions feel special",
  "Your family values are beautiful",
  "You bring people together naturally",
  "Your hosting skills are incredible",
  "You make gatherings more fun",
  "Your cooking smells like heaven",
  "You create the best atmospheres",
  "Your party planning is amazing",
  "You make everyone feel welcome",
  "Your social skills are impressive",
  "You're the life of every party",
  "Your conversation skills are unmatched",
  "You make small talk feel meaningful",
  "Your storytelling captivates everyone",
  "You have the best sense of humor",
  "Your timing is always perfect",
  "You make awkward moments comfortable",
  "Your charm is absolutely natural",
  "You're incredibly charismatic",
  "Your personality lights up rooms",
  "You make introductions feel easy",
  "Your networking skills amaze me",
  "You remember everyone's names",
  "Your thoughtfulness shows in details",
  "You make celebrations unforgettable",

  // August (31 days)
  "You're as golden as late summer",
  "Your maturity is incredibly beautiful",
  "You make endings feel like beginnings",
  "Your preparation skills are amazing",
  "You handle transitions so gracefully",
  "Your planning ahead impresses me",
  "You make busy times feel manageable",
  "Your organization skills are incredible",
  "You bring order to my chaos",
  "Your efficiency is so attractive",
  "You make productivity look effortless",
  "Your time management amazes me",
  "You balance everything so well",
  "Your multitasking skills are unreal",
  "You make hard work look easy",
  "Your dedication never goes unnoticed",
  "You're incredibly goal-oriented",
  "Your ambition is so inspiring",
  "You make success look natural",
  "Your work ethic is admirable",
  "You're incredibly professional",
  "Your leadership skills shine",
  "You make tough decisions look easy",
  "Your problem-solving is brilliant",
  "You handle pressure like a champion",
  "Your calm under stress amazes me",
  "You make challenges feel conquerable",
  "Your perseverance is beautiful",
  "You never give up on what matters",
  "Your determination is unstoppable",
  "You make achievement look graceful",

  // September (30 days)
  "You're as cozy as autumn begins",
  "Your wisdom feels like changing leaves",
  "You make new chapters exciting",
  "Your learning spirit is beautiful",
  "You embrace change so gracefully",
  "Your curiosity never stops amazing me",
  "You make education look fun",
  "Your intelligence is incredibly sexy",
  "You ask the most thoughtful questions",
  "Your insights are always profound",
  "You make complex things simple",
  "Your explanations are so clear",
  "You're an incredible teacher",
  "Your patience with learning is beautiful",
  "You make mistakes look like lessons",
  "Your growth mindset inspires me",
  "You're always improving yourself",
  "Your self-reflection is admirable",
  "You make personal development natural",
  "Your openness to feedback is rare",
  "You handle criticism with grace",
  "Your humility is so attractive",
  "You make learning from others look easy",
  "Your mentorship skills are amazing",
  "You guide others so naturally",
  "Your advice is always spot-on",
  "You make wisdom feel accessible",
  "Your life lessons are valuable",
  "You share knowledge so generously",
  "You make teaching feel like loving",

  // October (31 days)
  "You're as beautiful as autumn leaves",
  "Your transformation is always stunning",
  "You make change look magical",
  "Your seasonal style is incredible",
  "You embrace every phase beautifully",
  "Your adaptability amazes me constantly",
  "You make transitions feel natural",
  "Your flexibility is so admirable",
  "You handle uncertainty with grace",
  "Your resilience through change inspires me",
  "You make letting go look peaceful",
  "Your acceptance of life's cycles is wise",
  "You find beauty in every season",
  "Your appreciation for moments is deep",
  "You make temporary things feel eternal",
  "Your presence makes everything better",
  "You create magic in ordinary moments",
  "Your perspective shifts everything",
  "You make difficult times bearable",
  "Your comfort during hard times heals me",
  "You're my safe harbor in storms",
  "Your stability grounds me completely",
  "You make chaos feel manageable",
  "Your peace radiates to everyone",
  "You bring calm to frantic moments",
  "Your serenity is absolutely beautiful",
  "You make stress melt away",
  "Your tranquility is contagious",
  "You're my meditation and prayer",
  "Your stillness speaks volumes",
  "You make silence feel comfortable",

  // November (30 days)
  "You're everything I'm grateful for",
  "Your blessings in my life are countless",
  "You make thankfulness feel natural",
  "Your appreciation for life inspires me",
  "You find joy in simple things",
  "Your gratitude attitude is beautiful",
  "You make ordinary days feel special",
  "Your thankful heart touches mine",
  "You appreciate the little things",
  "Your recognition of beauty amazes me",
  "You make me count my blessings",
  "Your positive outlook is infectious",
  "You see good in everything",
  "Your optimism lifts my spirits",
  "You make hope feel realistic",
  "Your faith in good things inspires me",
  "You believe in happy endings",
  "Your trust in the process comforts me",
  "You make waiting feel worthwhile",
  "Your patience with timing is wise",
  "You understand seasons of life",
  "Your acceptance of God's plan is beautiful",
  "You make surrender look peaceful",
  "Your letting go teaches me",
  "You trust the journey completely",
  "Your faith in love never wavers",
  "You believe in us always",
  "Your commitment never falters",
  "You make forever feel possible",
  "Your love makes me believe in miracles",

  // December (31 days)
  "You're the best gift I've ever received",
  "Your love is my favorite present",
  "You make holidays feel magical",
  "Your Christmas spirit is infectious",
  "You bring joy to every celebration",
  "Your gift-giving is so thoughtful",
  "You make traditions feel special",
  "Your holiday cooking is incredible",
  "You create the coziest atmospheres",
  "Your decorating skills amaze me",
  "You make homes feel like havens",
  "Your hospitality is unmatched",
  "You welcome everyone with love",
  "Your generosity knows no bounds",
  "You give from your heart always",
  "Your selflessness is beautiful",
  "You put others first naturally",
  "Your caring nature is incredible",
  "You make giving feel better than receiving",
  "Your love language is acts of service",
  "You show love in countless ways",
  "Your thoughtfulness never stops",
  "You remember what matters to people",
  "Your attention to detail is amazing",
  "You make people feel seen and heard",
  "Your listening skills are incredible",
  "You're fully present in conversations",
  "Your empathy is your superpower",
  "You understand hearts without words",
  "Your intuition about people is spot-on",
  "You make this year end perfectly"
];

// Get today's compliment based on day of year
export function getTodaysCompliment(): string {
  const today = new Date();
  const start = new Date(today.getFullYear(), 0, 0);
  const diff = today.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  
  // Ensure we stay within bounds (handle leap years)
  const index = (dayOfYear - 1) % DAILY_COMPLIMENTS.length;
  return DAILY_COMPLIMENTS[index];
}
